services:
  app: 
    build: ./server
    image: my-flask-app
    volumes:
      - ./server:/app  # 로컬의 server 디렉토리를 컨테이너의 /app에 마운트
    ports:
      - 5000:5000
    depends_on:
      - chromadb
    env_file:
      - ./.env
    restart: always
    networks:
      - net

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  data:
    driver_opts:
      type: none
      device: ./vectorDB  # Using your preferred path under the back_api directory
      o: bind
